config {
  type: "table",
  description: "Data about the members of parliament in flat format",
  tags: ["mp_data"]
}

SELECT
  *
EXCEPT(updated_time, dataset_updated_date, party),
  `tanelis.functions.partyName`(party) AS party,
  `tanelis.functions.governmentOpposition`(party, term_start) AS parliament_group,
FROM
  ${ref("backup_mp_data_prod_flat")}
WHERE
  updated_time = (
    SELECT
      MAX(updated_time)
    FROM
      ${ref("backup_mp_data_prod_flat")}
  )
